name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@main
        with:
          host: 138.68.87.231
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /root/test_django_app/telegrambot
            source ./venv/bin/activate
            git pull
            python manage.py migrate
            python manage.py collectstatic --noinput
            supervisorctl restart all
